print('Wellcome to Student Management System:-')
a = input('Enter name of the Student:-')
b = int(input('Enter roll number of the Student:-'))
c = input('Enter the class of the Student:-')
d = input('Enter the Address of the Student:-')
e = input('Enter the Date of Birth of the Student:-')
f = int(input('Enter the Phone Number of The Student:-'))
g = input('Enter the Email id of the Student:-')
h = int(input('Enter the marks of the First Periodic:-'))
i = int(input('Enter the marks of the Second Periodic:-'))
j = int(input('Enter the marks of the Third Periodic:-'))
k = int(input('Enter the marks of the Fourth Periodic:-'))
l = ((h+i+j+k)/400)*100
print('Total Percentage = ',l)
